name: Schema
on: # Trigger the workflow on push or pull request, but only for the main branch
  push: {}
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pkg
        run: |
          pip install check-jsonschema

      - name: GH Workflows
        run: check-jsonschema .github/workflows/*.yml --builtin-schema "github-workflows"

      # - name: Azure Pipelines
      #   env:
      #     SCHEMA_FILE: https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/v1.204.0/service-schema.json
      #   run: check-jsonschema .azure-pipelines/*.yml --schemafile "$SCHEMA_FILE"
